import os
import math

################################################################################
# GENERATE MEMLIB
#
# Emit a Yosys memory_libmap .memlib file for a given SRAM macro.
# memory_libmap rewrites $mem_v2 cells into intermediate $__<NAME>_ cells
# keyed on this file; a companion techmap pass then binds those intermediate
# cells to the actual blackbox module (see generate_techmap.py).
#
# Naming convention: intermediate cell = "$__" + name.upper() + "_"
# e.g. fakeram45_512x32_1r1w  ->  $__FAKERAM45_512X32_1R1W_
#
# Port shapes dispatched on mem.macro_class:
#   1RW   - single srsw port (shared addr for read+write)
#   1R1W  - separate sr "R" + sw "W" with shared clock "CLK"
#   NR1W  - N sr "R0".."R{N-1}" + sw "W" with shared clock "CLK"
#   NRW   - N srsw "RW0".."RW{N-1}" with shared clock "CLK"
################################################################################

def intermediate_cell_name(macro_name):
    """Derive the intermediate cell name from the macro name."""
    return "$__" + macro_name.upper() + "_"


def generate_memlib(mem):
    mc   = getattr(mem, 'macro_class', '1RW')
    nr   = int(getattr(mem, 'num_r_ports', 1))
    name = mem.name
    aw   = math.ceil(math.log2(int(mem.depth)))
    w    = int(mem.width_in_bits)
    cell = intermediate_cell_name(name)

    lines = []
    lines.append(f'# memlib for {name}  (macro_class={mc})')
    lines.append(f'# Intermediate cell: {cell}')
    lines.append(f'# Generated by bsg_fakeram generate_memlib.py')
    lines.append(f'ram block \\{cell} {{')
    lines.append(f'    abits {aw};')
    lines.append(f'    width {w};')
    lines.append(f'    byte 1;   # per-bit write mask -> WR_EN width == data width')
    lines.append(f'    cost 64;')
    lines.append(f'    init none;')

    if mc == '1RW':
        lines.append(f'    port srsw "RW" {{')
        lines.append(f'        clock posedge;')
        lines.append(f'        rdwr undefined;')
        lines.append(f'    }}')

    elif mc == '1R1W':
        lines.append(f'    port sr "R" {{')
        lines.append(f'        clock posedge "CLK";')
        lines.append(f'    }}')
        lines.append(f'    port sw "W" {{')
        lines.append(f'        clock posedge "CLK";')
        lines.append(f'    }}')

    elif mc == 'NR1W':
        rd_names = ' '.join(f'"R{i}"' for i in range(nr))
        lines.append(f'    port sr {rd_names} {{')
        lines.append(f'        clock posedge "CLK";')
        lines.append(f'    }}')
        lines.append(f'    port sw "W" {{')
        lines.append(f'        clock posedge "CLK";')
        lines.append(f'    }}')

    elif mc == 'NRW':
        rw_names = ' '.join(f'"RW{i}"' for i in range(nr))
        lines.append(f'    port srsw {rw_names} {{')
        lines.append(f'        clock posedge "CLK";')
        lines.append(f'        rdwr no_change;')
        lines.append(f'    }}')

    else:
        # Unknown class: fallback to 1RW
        lines.append(f'    port srsw "RW" {{')
        lines.append(f'        clock posedge;')
        lines.append(f'        rdwr undefined;')
        lines.append(f'    }}')

    lines.append(f'}}')
    lines.append('')

    out = os.sep.join([mem.results_dir, name + '.memlib'])
    with open(out, 'w') as f:
        f.write('\n'.join(lines))
