"""Yosys memory_libmap .memlib generator (shape-aware).

Emits one ram block per macro:
    rw ports → port srsw "RW0".."RW{rw-1}"
    r  ports → port sr   "R0".."R{r-1}"
    w  ports → port sw   "W0".."W{w-1}"
all on a shared posedge "CLK".

memory_libmap rewrites $mem_v2 cells into intermediate "$__<NAME>_" cells
keyed on this file; generate_techmap.py emits the companion module that
binds those intermediate cells to the actual blackbox.
"""
import os
import math

from utils.port_shape import all_port_pins, memlib_port_name


def intermediate_cell_name(macro_name: str) -> str:
    return "$__" + macro_name.upper() + "_"


def generate_memlib(mem) -> None:
    name = mem.name
    aw   = max(1, math.ceil(math.log2(int(mem.depth))))
    w    = int(mem.width_in_bits)
    cell = intermediate_cell_name(name)
    shape = mem.shape

    lines = [
        f'# memlib for {name}  (port_shape rw={shape.rw} r={shape.r} w={shape.w})',
        f'# Intermediate cell: {cell}',
        f'# Generated by bsg_fakeram generate_memlib.py',
        f'ram block \\{cell} {{',
        f'    abits {aw};',
        f'    width {w};',
        f'    byte 1;   # per-bit write mask -> WR_EN width == data width',
        f'    cost 64;',
        f'    init none;',
    ]

    # Group port labels by srsw / sr / sw so each kind gets one `port` block.
    rw_labels = [memlib_port_name('rw', i) for i in range(shape.rw)]
    r_labels  = [memlib_port_name('r',  i) for i in range(shape.r)]
    w_labels  = [memlib_port_name('w',  i) for i in range(shape.w)]

    if rw_labels:
        names = ' '.join(f'"{n}"' for n in rw_labels)
        lines += [
            f'    port srsw {names} {{',
            f'        clock posedge "CLK";',
            f'        rdwr no_change;',
            f'    }}',
        ]
    if r_labels:
        names = ' '.join(f'"{n}"' for n in r_labels)
        lines += [
            f'    port sr {names} {{',
            f'        clock posedge "CLK";',
            f'    }}',
        ]
    if w_labels:
        names = ' '.join(f'"{n}"' for n in w_labels)
        lines += [
            f'    port sw {names} {{',
            f'        clock posedge "CLK";',
            f'    }}',
        ]

    lines.append('}')
    lines.append('')

    out = os.sep.join([mem.results_dir, name + '.memlib'])
    with open(out, 'w') as f:
        f.write('\n'.join(lines))
