"""Yosys techmap generator (shape-aware).

Emits one Verilog module that maps the intermediate "$__<NAME>_" cell
produced by memory_libmap onto the real blackbox <NAME>. Pin contract:

    Yosys signal                       blackbox pin
    --------------------------------   ----------------------------
    CLK_CLK                            clk
    (tied)                             ce_in           = 1'b1

    PORT_RW{i}_ADDR                    rw_addr_in_{i}
    PORT_RW{i}_RD_DATA                 rw_rd_out_{i}
    PORT_RW{i}_WR_DATA                 rw_wd_in_{i}
    PORT_RW{i}_WR_EN                   rw_w_mask_in_{i}    (mask-width)
    (derived)                          rw_we_in_{i}        = |WR_EN

    PORT_R{i}_ADDR                     r_addr_in_{i}
    PORT_R{i}_RD_DATA                  r_rd_out_{i}

    PORT_W{i}_ADDR                     w_addr_in_{i}
    PORT_W{i}_WR_DATA                  w_wd_in_{i}
    PORT_W{i}_WR_EN                    w_w_mask_in_{i}     (mask-width)
    (derived)                          w_we_in_{i}         = |WR_EN

`byte 1` in .memlib makes WR_EN data-width, so it doubles as the per-bit
write mask. The scalar we_in is the OR-reduction of the mask bits.
"""
import os
import math

from utils.port_shape import all_port_pins, techmap_signal


def generate_techmap(mem) -> None:
    name  = mem.name
    aw    = max(1, math.ceil(math.log2(int(mem.depth))))
    w     = int(mem.width_in_bits)
    shape = mem.shape
    cell  = "$__" + name.upper() + "_"

    ports: list[str] = ['input  CLK_CLK']
    conn:  list[str] = [f'.clk    (CLK_CLK)', f".ce_in  (1'b1)"]

    for kind, pins in all_port_pins(shape):
        if kind == 'rw':
            i = int(pins['addr'].rsplit('_', 1)[1])
            ports.append(f'input  [{aw-1}:0] {techmap_signal("rw", i, "ADDR")}')
            ports.append(f'output [{w-1}:0]  {techmap_signal("rw", i, "RD_DATA")}')
            ports.append(f'input  [{w-1}:0]  {techmap_signal("rw", i, "WR_DATA")}')
            ports.append(f'input  [{w-1}:0]  {techmap_signal("rw", i, "WR_EN")}')
            conn.append(f'.{pins["addr"]}  ({techmap_signal("rw", i, "ADDR")})')
            conn.append(f'.{pins["rd"]}    ({techmap_signal("rw", i, "RD_DATA")})')
            conn.append(f'.{pins["wd"]}    ({techmap_signal("rw", i, "WR_DATA")})')
            conn.append(f'.{pins["wmask"]} ({techmap_signal("rw", i, "WR_EN")})')
            conn.append(f'.{pins["we"]}    (|{techmap_signal("rw", i, "WR_EN")})')
        elif kind == 'r':
            i = int(pins['addr'].rsplit('_', 1)[1])
            ports.append(f'input  [{aw-1}:0] {techmap_signal("r", i, "ADDR")}')
            ports.append(f'output [{w-1}:0]  {techmap_signal("r", i, "RD_DATA")}')
            conn.append(f'.{pins["addr"]} ({techmap_signal("r", i, "ADDR")})')
            conn.append(f'.{pins["rd"]}   ({techmap_signal("r", i, "RD_DATA")})')
        elif kind == 'w':
            i = int(pins['addr'].rsplit('_', 1)[1])
            ports.append(f'input  [{aw-1}:0] {techmap_signal("w", i, "ADDR")}')
            ports.append(f'input  [{w-1}:0]  {techmap_signal("w", i, "WR_DATA")}')
            ports.append(f'input  [{w-1}:0]  {techmap_signal("w", i, "WR_EN")}')
            conn.append(f'.{pins["addr"]}  ({techmap_signal("w", i, "ADDR")})')
            conn.append(f'.{pins["wd"]}    ({techmap_signal("w", i, "WR_DATA")})')
            conn.append(f'.{pins["wmask"]} ({techmap_signal("w", i, "WR_EN")})')
            conn.append(f'.{pins["we"]}    (|{techmap_signal("w", i, "WR_EN")})')

    p_str = ',\n    '.join(ports)
    c_str = ',\n        '.join(conn)
    body = (
        f'module \\{cell} (\n'
        f'    {p_str}\n'
        f');\n'
        f'    {name} _TECHMAP_REPLACE_ (\n'
        f'        {c_str}\n'
        f'    );\n'
        f'endmodule'
    )

    header = (
        f'// Yosys techmap stub for {name}\n'
        f'//   port_shape: rw={shape.rw} r={shape.r} w={shape.w}\n'
        f'//   intermediate cell: {cell}\n'
        f'// Generated by bsg_fakeram generate_techmap.py\n'
    )

    out = os.sep.join([mem.results_dir, name + '.techmap.v'])
    with open(out, 'w') as f:
        f.write(header + '\n' + body + '\n')
