import os
import math

################################################################################
# GENERATE TECHMAP
#
# Emit a Yosys techmap Verilog file for a given SRAM macro.
#
# memory_libmap rewrites $mem_v2 cells into intermediate "$__<NAME>_" cells.
# This techmap then replaces those intermediate cells with _TECHMAP_REPLACE_
# instantiations of the real blackbox (named by mem.name).
#
# Port signal naming (Yosys memory_libmap conventions):
#   Unnamed clock  → PORT_<portname>_CLK   (e.g. PORT_RW_CLK for 1RW)
#   Named clock "CLK" → single shared CLK_CLK signal
#   srsw port "P" → PORT_P_ADDR, PORT_P_RD_DATA, PORT_P_WR_DATA, PORT_P_WR_EN
#   sr   port "P" → PORT_P_ADDR, PORT_P_RD_DATA
#   sw   port "P" → PORT_P_ADDR, PORT_P_WR_DATA, PORT_P_WR_EN
#
# byte 1 in .memlib → PORT_*_WR_EN width == data width → mapped to w_mask_in.
# we_in derived as |WR_EN (OR-reduction across mask bits).
# ce_in tied 1'b1 (no chip-enable in the memlib model).
################################################################################


def generate_techmap(mem):
    mc   = getattr(mem, 'macro_class', '1RW')
    nr   = int(getattr(mem, 'num_r_ports', 1))
    name = mem.name
    aw   = math.ceil(math.log2(int(mem.depth)))
    w    = int(mem.width_in_bits)
    cell = "$__" + name.upper() + "_"

    if mc == '1R1W':
        body = _body_1r1w(name, cell, aw, w)
    elif mc == 'NR1W':
        body = _body_nr1w(name, cell, aw, w, nr)
    elif mc == 'NRW':
        body = _body_nrw(name, cell, aw, w, nr)
    else:
        body = _body_1rw(name, cell, aw, w)

    header = (
        f'// Yosys techmap stub for {name}  (macro_class={mc})\n'
        f'// Generated by bsg_fakeram generate_techmap.py\n'
        f'// Intermediate cell: {cell}\n'
    )

    out = os.sep.join([mem.results_dir, name + '.techmap.v'])
    with open(out, 'w') as f:
        f.write(header + '\n' + body + '\n')


def _module(cell, ports, inst_name, conn):
    """Render a techmap module with one _TECHMAP_REPLACE_ instance."""
    p_str = ',\n    '.join(ports)
    c_str = ',\n        '.join(conn)
    return (
        f'module \\{cell} (\n'
        f'    {p_str}\n'
        f');\n'
        f'    {inst_name} _TECHMAP_REPLACE_ (\n'
        f'        {c_str}\n'
        f'    );\n'
        f'endmodule'
    )


def _body_1rw(name, cell, aw, w):
    # port srsw "RW" { clock posedge; }  — unnamed clock → PORT_RW_CLK
    ports = [
        f'input  PORT_RW_CLK',
        f'input  [{aw-1}:0] PORT_RW_ADDR',
        f'output [{w-1}:0]  PORT_RW_RD_DATA',
        f'input  [{w-1}:0]  PORT_RW_WR_DATA',
        f'input  [{w-1}:0]  PORT_RW_WR_EN',
    ]
    conn = [
        ".clk       (PORT_RW_CLK)",
        ".ce_in     (1'b1)",
        ".addr_in   (PORT_RW_ADDR)",
        ".rd_out    (PORT_RW_RD_DATA)",
        ".wd_in     (PORT_RW_WR_DATA)",
        ".w_mask_in (PORT_RW_WR_EN)",
        ".we_in     (|PORT_RW_WR_EN)",
    ]
    return _module(cell, ports, name, conn)


def _body_1r1w(name, cell, aw, w):
    # port sr "R" { clock posedge "CLK"; }
    # port sw "W" { clock posedge "CLK"; }  — shared clock → CLK_CLK
    ports = [
        'input  CLK_CLK',
        f'input  [{aw-1}:0] PORT_R_ADDR',
        f'output [{w-1}:0]  PORT_R_RD_DATA',
        f'input  [{aw-1}:0] PORT_W_ADDR',
        f'input  [{w-1}:0]  PORT_W_WR_DATA',
        f'input  [{w-1}:0]  PORT_W_WR_EN',
    ]
    conn = [
        ".clk        (CLK_CLK)",
        ".ce_in      (1'b1)",
        ".rd_addr_in (PORT_R_ADDR)",
        ".rd_out     (PORT_R_RD_DATA)",
        ".wr_addr_in (PORT_W_ADDR)",
        ".wd_in      (PORT_W_WR_DATA)",
        ".w_mask_in  (PORT_W_WR_EN)",
        ".we_in      (|PORT_W_WR_EN)",
    ]
    return _module(cell, ports, name, conn)


def _body_nr1w(name, cell, aw, w, nr):
    # port sr "R0"..."R{N-1}" { clock posedge "CLK"; }
    # port sw "W"             { clock posedge "CLK"; }  — shared clock → CLK_CLK
    ports = ['input  CLK_CLK']
    for i in range(nr):
        ports.append(f'input  [{aw-1}:0] PORT_R{i}_ADDR')
        ports.append(f'output [{w-1}:0]  PORT_R{i}_RD_DATA')
    ports.append(f'input  [{aw-1}:0] PORT_W_ADDR')
    ports.append(f'input  [{w-1}:0]  PORT_W_WR_DATA')
    ports.append(f'input  [{w-1}:0]  PORT_W_WR_EN')

    conn = [".clk        (CLK_CLK)", ".ce_in      (1'b1)"]
    for i in range(nr):
        conn.append(f'.rd_addr_in_{i} (PORT_R{i}_ADDR)')
        conn.append(f'.rd_out_{i}     (PORT_R{i}_RD_DATA)')
    conn.append('.wr_addr_in (PORT_W_ADDR)')
    conn.append('.wd_in      (PORT_W_WR_DATA)')
    conn.append('.w_mask_in  (PORT_W_WR_EN)')
    conn.append('.we_in      (|PORT_W_WR_EN)')

    return _module(cell, ports, name, conn)


def _body_nrw(name, cell, aw, w, nr):
    # port srsw "RW0"..."RW{N-1}" { clock posedge "CLK"; rdwr no_change; }
    # shared clock → CLK_CLK
    ports = ['input  CLK_CLK']
    for i in range(nr):
        ports.append(f'input  [{aw-1}:0] PORT_RW{i}_ADDR')
        ports.append(f'output [{w-1}:0]  PORT_RW{i}_RD_DATA')
        ports.append(f'input  [{w-1}:0]  PORT_RW{i}_WR_DATA')
        ports.append(f'input  [{w-1}:0]  PORT_RW{i}_WR_EN')

    conn = [".clk    (CLK_CLK)", ".ce_in  (1'b1)"]
    for i in range(nr):
        conn.append(f'.rw_addr_in_{i}   (PORT_RW{i}_ADDR)')
        conn.append(f'.rw_rd_out_{i}    (PORT_RW{i}_RD_DATA)')
        conn.append(f'.rw_wd_in_{i}     (PORT_RW{i}_WR_DATA)')
        conn.append(f'.rw_w_mask_in_{i} (PORT_RW{i}_WR_EN)')
        conn.append(f'.rw_we_in_{i}     (|PORT_RW{i}_WR_EN)')

    return _module(cell, ports, name, conn)
